### ISSUE TITLE
代理https tls双向认证

### ISSUE THREAD

**Issue by zhao173205** [jichangfeng/kong-http-proxy#1]
作者您好，
当我想要用这个插件去代理kong https双向认证的请求，发现请求转发出去并没又携带客户端证书导致请求无法转发这个问题需要怎么配置能解决呢

**Comment by jichangfeng** [comment]
[60e1aba](https://github.com/jichangfeng/kong-http-proxy/commit/60e1aba9aa28296a02d85dd6b4d8cc7f0ead4d4d) - 增加支持配置客户端证书和私钥

**Comment by zhao173205** [comment]
作者您好，据我了解OpenResty 1.21.4.2 RC1 才将内置lua-nginx-module升级到 v0.10.24。而最新的kong 3.3.0使用的是openresty/1.21.4.1 中内置ngx_lua-0.10.21 而文件使用的ssl_client_cert 和ssl_client_priv_key使用版本限制是ngx_lua_http_module >= v0.10.23. 所以我认为应该不能解决mtls的问题
